import React, { useEffect, useState } from "react";
import { Form, Select, Input, Button, Switch, Alert, App, theme } from "antd";
import { LockOutlined, WarningOutlined, SyncOutlined } from "@ant-design/icons";
import { useTranslation } from "@refinedev/core";
import { getAvailableOrderTransitions, getStatusOptions } from "../../../constants/orders";
import { supabaseClient } from "../../../providers/supabase-client";
import { getFunctionsErrorMessage } from "../../../utils/functions-error";
import { formatDisplayLabel } from "../helpers";
import type { OrderRecord } from "../types";

const TERMINAL_STATUSES = ["delivered", "cancelled"];
const LOCKED_STATUSES = ["delivered", "cancelled"];
const FULFILLMENT_STATUSES_REQUIRING_SETTLEMENT = ["processing", "awaiting_shipment", "shipped", "in_transit", "delivered"];

interface OrderActionFormProps {
  record?: OrderRecord;
  refreshOrderState: () => Promise<void>;
}

export const OrderActionForm: React.FC<OrderActionFormProps> = ({ record, refreshOrderState }) => {
  const { translate } = useTranslation();
  const { token } = theme.useToken();
  const { modal } = App.useApp();
  const [form] = Form.useForm<{ status: string; waybill_number?: string; waybill_override_reason?: string }>();
  
  const [syncing, setSyncing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [manualWaybillMode, setManualWaybillMode] = useState(false);

  const hasBiteship = !!record?.biteship_order_id;
  const hasProviderManagedShipment =
    hasBiteship || !!record?.biteship_tracking_id || record?.waybill_source === "system";
  const currentStatus = record?.status ?? "";
  const isPaymentSettled = record?.payment_status === "settlement";
  const isTerminalStatus = TERMINAL_STATUSES.includes(currentStatus);
  const canSyncTracking = hasBiteship && !isTerminalStatus && isPaymentSettled;
  const showTrackingPaymentGuard = hasBiteship && !isTerminalStatus && !isPaymentSettled;

  const isStatusDropdownLocked = LOCKED_STATUSES.includes(currentStatus);
  const isFormDisabled = isTerminalStatus;
  const isWaybillFullyLocked = ["shipped", "delivered"].includes(currentStatus);
  const isWaybillAutoGenerated = hasProviderManagedShipment && !!record?.waybill_number;
  const showManualWaybillToggle = hasProviderManagedShipment && !isWaybillFullyLocked;
  const showManualWaybillField = !hasProviderManagedShipment || manualWaybillMode;
  const isWaybillInputDisabled = isWaybillFullyLocked;
  const showOverrideReason = manualWaybillMode && hasBiteship && !isWaybillFullyLocked;
  const requiresManualWaybillForSelectedStatus = (status: string) =>
    status === "shipped" && (!hasProviderManagedShipment || manualWaybillMode);

  useEffect(() => {
    if (record) {
      form.setFieldsValue({ status: record.status ?? "pending", waybill_number: record.waybill_number ?? "" });
    }
  }, [record, form]);

  const invokeOrderManager = async (values: {
    action: "transition_status" | "sync_tracking";
    orderId: string;
    payload?: Record<string, unknown>;
  }) => {
    const { data, error } = await supabaseClient.functions.invoke("order-manager", {
      body: values,
    });
    if (error) {
      const msg = await getFunctionsErrorMessage(error, "Order manager request failed");
      throw new Error(msg);
    }
    return data;
  };

  const handleSyncTracking = async () => {
    if (!record?.biteship_order_id || isTerminalStatus) return;
    if (!isPaymentSettled) {
      modal.error({
        title: translate("orders.paymentGuard.syncTitle"),
        content: translate("orders.paymentGuard.syncDescription"),
      });
      return;
    }

    setSyncing(true);
    try {
      const result = await invokeOrderManager({
        action: "sync_tracking",
        orderId: record.id,
      });

      const syncedStatus = typeof result?.data?.status === "string" ? result.data.status : undefined;
      const syncedStatusLabel = syncedStatus
        ? translate(`orderStatus.${syncedStatus}`, {}, formatDisplayLabel(syncedStatus))
        : translate("orders.trackingSynced");

      modal.success({
        title: translate("orders.trackingSynced"),
        content: translate("orders.trackingSyncSuccess", { status: syncedStatusLabel }, `Status updated to ${syncedStatusLabel}`),
      });
      await refreshOrderState();
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      modal.error({ title: translate("orders.syncFailed"), content: msg });
    } finally {
      setSyncing(false);
    }
  };

  const doMutate = async (values: { status: string; waybill_number?: string; waybill_override_reason?: string }) => {
    if (!record?.id) return;

    setSaving(true);
    try {
      const payload: Record<string, unknown> = {
        to: values.status,
        waybill_number: values.waybill_number?.trim() || undefined,
      };

      if (manualWaybillMode && hasBiteship && values.waybill_number?.trim()) {
        payload.waybill_source = "manual";
        payload.waybill_override_reason = values.waybill_override_reason?.trim() || undefined;
      } else if (values.waybill_number?.trim() && !hasBiteship) {
        payload.waybill_source = "manual";
      }

      await invokeOrderManager({
        action: "transition_status",
        orderId: record.id,
        payload,
      });

      modal.success({
        title: translate("notifications.success"),
        content: translate("orders.saveSuccess"),
      });
      setManualWaybillMode(false);
      await refreshOrderState();
    } catch (err) {
      const msg = err instanceof Error ? err.message : translate("orders.saveError");
      modal.error({
        title: translate("notifications.error"),
        content: msg,
      });
    } finally {
      setSaving(false);
    }
  };

  const handleUpdate = (values: { status: string; waybill_number?: string; waybill_override_reason?: string }) => {
    const isBlockedFulfillmentTransition = !isPaymentSettled && FULFILLMENT_STATUSES_REQUIRING_SETTLEMENT.includes(values.status);

    if (isBlockedFulfillmentTransition) {
      modal.error({
        title: translate("orders.paymentGuard.transitionTitle"),
        content: translate("orders.paymentGuard.transitionDescription"),
      });
      return;
    }

    if (values.status === "cancelled") {
      const cancelContentKey = isPaymentSettled ? "orders.cancelContentPaid" : "orders.cancelContentUnpaid";
      modal.confirm({
        title: translate("orders.cancelConfirm"),
        content: translate(cancelContentKey),
        okText: translate("orders.cancelOk"),
        cancelText: translate("orders.cancelButton"),
        okButtonProps: { danger: true },
        onOk: () => doMutate(values),
      });
      return;
    }
    doMutate(values);
  };

  const STATUS_OPTIONS = getStatusOptions(translate);
  const current = record?.status ?? "";
  const allowed = getAvailableOrderTransitions(current, {
    hasProviderManagedShipment,
    allowManualWaybillOverride: manualWaybillMode,
  });
  const paymentSafeAllowed = isPaymentSettled
    ? allowed
    : allowed.filter((status) => !FULFILLMENT_STATUSES_REQUIRING_SETTLEMENT.includes(status));
  const blockedFulfillmentTransitions = allowed.filter(
    (status) => !paymentSafeAllowed.includes(status) && FULFILLMENT_STATUSES_REQUIRING_SETTLEMENT.includes(status),
  );
  const baseOptions = isStatusDropdownLocked
    ? STATUS_OPTIONS.filter((opt) => opt.value === current)
    : STATUS_OPTIONS.filter((opt) => paymentSafeAllowed.includes(String(opt.value)));
  const currentInOptions = baseOptions.some((opt) => opt.value === current);
  const availableStatusOptions = currentInOptions
    ? baseOptions
    : [...baseOptions, { value: current, label: translate(`orderStatus.${current}`, {}, formatDisplayLabel(current)) }];
  const hasRealNextStatusTransition = availableStatusOptions.some(
    (option) => option.value !== current,
  );
  const isSaveDisabled = isFormDisabled || !hasRealNextStatusTransition;
  const hasPaymentGuardedFulfillment = blockedFulfillmentTransitions.length > 0;
  
  return (
    <>
      {hasPaymentGuardedFulfillment && (
        <Alert
          style={{ marginTop: token.marginMD }}
          type="warning"
          showIcon
          message={translate("orders.paymentGuard.transitionTitle")}
          description={translate("orders.paymentGuard.transitionDescription")}
        />
      )}

      {showTrackingPaymentGuard && (
        <Alert
          style={{ marginTop: token.marginMD }}
          type="warning"
          showIcon
          message={translate("orders.paymentGuard.syncTitle")}
          description={translate("orders.paymentGuard.syncDescription")}
        />
      )}

      {canSyncTracking && (
        <div style={{ marginTop: token.marginMD }}>
          <Button type="default" icon={<SyncOutlined spin={syncing} />} onClick={handleSyncTracking} loading={syncing}>
            {translate("orders.syncTracking")}
          </Button>
        </div>
      )}

      {hasProviderManagedShipment && !manualWaybillMode && !isWaybillFullyLocked && (
        <Alert
          style={{ marginTop: token.marginMD, marginBottom: token.marginMD }}
          type="info"
          showIcon
          message={translate("orders.providerManagedWaybillHelp")}
        />
      )}

      <Form form={form} layout="vertical" onFinish={handleUpdate} initialValues={{ status: record?.status ?? "pending", waybill_number: record?.waybill_number ?? "" }}>
        <Form.Item
          name="status"
          label={translate("orders.nextOrderStatus")}
          rules={[{ required: true }]}
          tooltip={isStatusDropdownLocked ? translate("orders.tooltips.statusSystemControlled") : undefined}
        >
          <Select options={availableStatusOptions} style={{ minWidth: 160 }} disabled={isStatusDropdownLocked || isSaveDisabled} />
        </Form.Item>

        {showManualWaybillToggle && (
          <Form.Item label={translate("orders.enableManualWaybill")}>
            <Switch
              size="small"
              checked={manualWaybillMode}
              onChange={setManualWaybillMode}
              checkedChildren={translate("orders.waybillModeManual")}
              unCheckedChildren={translate("orders.waybillModeAuto")}
            />
          </Form.Item>
        )}

        {showManualWaybillField && (
          <Form.Item
            name="waybill_number"
            label={translate("orders.fields.waybillNumber")}
            tooltip={isWaybillFullyLocked
              ? translate("orders.tooltips.waybillLocked")
              : isWaybillAutoGenerated
                ? translate("orders.tooltips.waybillAuto")
                : translate("orders.tooltips.waybillManual")}
            dependencies={["status"]}
            rules={[
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!requiresManualWaybillForSelectedStatus(String(getFieldValue("status") ?? ""))) {
                    return Promise.resolve();
                  }
                  if (String(value ?? "").trim()) return Promise.resolve();
                  const shippedStatusLabel = translate("orderStatus.shipped", {}, formatDisplayLabel("shipped"));
                  return Promise.reject(new Error(translate("orders.waybillRequired", { status: shippedStatusLabel })));
                },
              }),
            ]}
          >
            <Input
              placeholder={translate("orders.waybillPlaceholder")}
              disabled={isWaybillInputDisabled || isSaveDisabled}
              suffix={isWaybillFullyLocked ? <LockOutlined aria-label={translate("orders.accessibility.waybillLocked")} style={{ color: token.colorTextTertiary }} /> : undefined}
            />
          </Form.Item>
        )}

        {showOverrideReason && (
          <>
            <Alert
              message={translate("orders.manualWaybillWarning")}
              type="warning"
              showIcon
              icon={<WarningOutlined />}
              style={{ marginBottom: token.marginMD }}
            />
            <Form.Item
              name="waybill_override_reason"
              label={translate("orders.waybillOverrideReason")}
              rules={[{ required: true, message: translate("orders.waybillOverridePlaceholder") }]}
            >
              <Input.TextArea
                placeholder={translate("orders.waybillOverridePlaceholder")}
                rows={2}
              />
            </Form.Item>
          </>
        )}

        <Form.Item>
          <Button type="primary" htmlType="submit" loading={saving} disabled={isSaveDisabled}>
            {translate("buttons.save")}
          </Button>
        </Form.Item>
      </Form>
    </>
  );
};
