ALTER TABLE public.addresses DROP COLUMN IF EXISTS province_id; 
 ALTER TABLE public.addresses DROP COLUMN IF EXISTS city_id; 
 ALTER TABLE public.addresses DROP COLUMN IF EXISTS district_id; 
 ALTER TABLE public.addresses DROP COLUMN IF EXISTS subdistrict_id; 
 ALTER TABLE public.addresses ADD COLUMN IF NOT EXISTS latitude text; 
 ALTER TABLE public.addresses ADD COLUMN IF NOT EXISTS longitude text; 
 ALTER TABLE public.addresses ADD COLUMN IF NOT EXISTS area_id text; 
 ALTER TABLE public.orders DROP COLUMN IF EXISTS origin_city_id; 
 ALTER TABLE public.orders DROP COLUMN IF EXISTS destination_city_id; 
 ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS origin_area_id text; 
 ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS destination_area_id text; 
 ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS biteship_order_id text;
