import { useCallback, useEffect, useState } from "react";
import { useShow, useTranslation } from "@refinedev/core";
import { Show, DateField, NumberField } from "@refinedev/antd";
import { Typography, Table, Tag, Descriptions, Form, Select, Input, Button, Card, App, Timeline, Spin, Tooltip, Switch, Alert, Space } from "antd";
import { SyncOutlined, InfoCircleOutlined, LockOutlined, WarningOutlined } from "@ant-design/icons";
import {
  STATUS_COLORS,
  PAYMENT_COLORS,
  getAvailableOrderTransitions,
  getStatusOptions,
} from "../../constants/orders";
import { getFallbackCourierOption } from "../../constants/couriers";
import { supabaseClient } from "../../providers/supabase-client";
import { getFunctionsErrorMessage } from "../../utils/functions-error";

const { Title, Text } = Typography;

interface OrderItem {
  id: string;
  product_id: string;
  quantity: number;
  price_at_purchase: string | number;
  products?: { name: string } | null;
}

interface OrderRecord {
  id: string;
  user_id: string;
  total_amount: string | number;
  status: string;
  payment_status: string;
  shipping_cost?: string | number | null;
  courier_code?: string | null;
  courier_service?: string | null;
  shipping_etd?: string | null;
  waybill_number?: string | null;
  waybill_source?: string | null;
  payment_type?: string | null;
  midtrans_order_id?: string | null;
  midtrans_transaction_id?: string | null;
  biteship_order_id?: string | null;
  biteship_tracking_id?: string | null;
  created_at: string;
  updated_at?: string | null;
  order_items?: OrderItem[];
}

interface Activity {
  id: string;
  action: string;
  old_status: string | null;
  new_status: string | null;
  actor_type: string;
  metadata: Record<string, unknown>;
  created_at: string;
}

interface BiteshipExceptionInfo {
  status: string;
  alertType: "warning" | "error" | "info";
  messageKey: string;
}

// Statuses where the status dropdown is locked (terminal states)
const TERMINAL_STATUSES = ["delivered", "cancelled"];
// Only lock for terminal statuses - shipped can still transition to delivered
const LOCKED_STATUSES = ["delivered", "cancelled"];

const formatDisplayLabel = (value: string | null | undefined) => {
  if (!value) {
    return "-";
  }

  return value
    .split(/[_-]/g)
    .filter(Boolean)
    .map((part) => (part.length <= 3 ? part.toUpperCase() : `${part.charAt(0).toUpperCase()}${part.slice(1)}`))
    .join(" ");
};

const formatBiteshipStatusLabel = (value: string | null | undefined) => {
  if (!value) {
    return "-";
  }

  return value
    .split(/[_-]/g)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(" ");
};

export const OrderShow: React.FC = () => {
  const { translate } = useTranslation();
  // Order reads already resolve through the `orders` -> `order_read_model`
  // mapping in the data provider. That provider also hydrates `order_items`
  // separately, so this page intentionally avoids a nested select here.
  const { result: record, query } = useShow<OrderRecord>();
  const { isLoading } = query;

  const { modal } = App.useApp();
  const [form] = Form.useForm<{ status: string; waybill_number?: string; waybill_override_reason?: string }>();
  const [activities, setActivities] = useState<Activity[]>([]);
  const [loadingActivities, setLoadingActivities] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [manualWaybillMode, setManualWaybillMode] = useState(false);

  const items = record?.order_items ?? [];
  const hasBiteship = !!record?.biteship_order_id;
  const hasProviderManagedShipment =
    hasBiteship || !!record?.biteship_tracking_id || record?.waybill_source === "system";
  const currentStatus = record?.status ?? "";
  const canSyncTracking = hasBiteship && !TERMINAL_STATUSES.includes(currentStatus);

  // Status dropdown lock: only lock for terminal statuses (delivered, cancelled)
  // shipped CAN still transition to delivered, so don't lock it
  const isStatusDropdownLocked = LOCKED_STATUSES.includes(currentStatus);

  // Save button: disabled only for terminal statuses
  const isFormDisabled = TERMINAL_STATUSES.includes(currentStatus);

  // Waybill fully locked after shipped/delivered — no override possible
  const isWaybillFullyLocked = ["shipped", "delivered"].includes(currentStatus);

  const isWaybillAutoGenerated = hasProviderManagedShipment && !!record?.waybill_number;
  const showManualWaybillToggle = hasProviderManagedShipment && !isWaybillFullyLocked;
  const showManualWaybillField = !hasProviderManagedShipment || manualWaybillMode;
  const isWaybillInputDisabled = isWaybillFullyLocked;
  const showOverrideReason = manualWaybillMode && hasBiteship && !isWaybillFullyLocked;
  const requiresManualWaybillForSelectedStatus = (status: string) =>
    status === "shipped" && (!hasProviderManagedShipment || manualWaybillMode);

  const latestSyncActivity = activities.find((activity) => activity.action === "sync_tracking");

  const latestBiteshipException = latestSyncActivity && typeof latestSyncActivity.metadata?.biteship_exception_status === "string"
    ? latestSyncActivity
    : undefined;

  const biteshipExceptionInfo: BiteshipExceptionInfo | null = latestBiteshipException
    ? {
        status: String(latestBiteshipException.metadata.biteship_exception_status),
        alertType: (String(latestBiteshipException.metadata.biteship_exception_alert_type || "warning") as BiteshipExceptionInfo["alertType"]),
        messageKey: String(latestBiteshipException.metadata.biteship_exception_message_key || ""),
      }
    : null;

  const loadActivities = useCallback(async () => {
    if (!record?.id) return;
    setLoadingActivities(true);
    try {
      const { data, error } = await supabaseClient
        .from("order_activities")
        .select("*")
        .eq("order_id", record.id)
        .order("created_at", { ascending: false })
        .limit(20);

      if (!error && data) {
        setActivities(data as Activity[]);
      }
    } catch (err) {
      console.error("Failed to load activities:", err);
    } finally {
      setLoadingActivities(false);
    }
  }, [record?.id]);

  useEffect(() => {
    if (record?.id) {
      loadActivities();
    }
  }, [record?.id, loadActivities]);

  const refreshOrderState = useCallback(async () => {
    await query.refetch();
    await loadActivities();
  }, [loadActivities, query]);

  const invokeOrderManager = async (values: {
    action: "transition_status" | "sync_tracking";
    orderId: string;
    payload?: Record<string, unknown>;
  }) => {
    const { data, error } = await supabaseClient.functions.invoke("order-manager", {
      body: values,
    });
    if (error) {
      const msg = await getFunctionsErrorMessage(error, "Order manager request failed");
      throw new Error(msg);
    }
    return data;
  };

  const handleSyncTracking = async () => {
    if (!record?.biteship_order_id || !canSyncTracking) return;
    setSyncing(true);
    try {
      const result = await invokeOrderManager({
        action: "sync_tracking",
        orderId: record.id,
      });

      const syncedStatus = typeof result?.data?.status === "string" ? result.data.status : undefined;
      const syncedStatusLabel = syncedStatus
        ? translate(`orderStatus.${syncedStatus}`, {}, formatDisplayLabel(syncedStatus))
        : translate("orders.trackingSynced");

      modal.success({
        title: translate("orders.trackingSynced"),
        content: translate("orders.trackingSyncSuccess", { status: syncedStatusLabel }, `Status updated to ${syncedStatusLabel}`),
      });
      await refreshOrderState();
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      modal.error({ title: translate("orders.syncFailed"), content: msg });
    } finally {
      setSyncing(false);
    }
  };

  const doMutate = async (values: { status: string; waybill_number?: string; waybill_override_reason?: string }) => {
    if (!record?.id) return;

    setSaving(true);
    try {
      const payload: Record<string, unknown> = {
        to: values.status,
        waybill_number: values.waybill_number?.trim() || undefined,
      };

      // If manual waybill mode is on and there's a Biteship order, mark as manual override
      if (manualWaybillMode && hasBiteship && values.waybill_number?.trim()) {
        payload.waybill_source = "manual";
        payload.waybill_override_reason = values.waybill_override_reason?.trim() || undefined;
      } else if (values.waybill_number?.trim() && !hasBiteship) {
        payload.waybill_source = "manual";
      }

      await invokeOrderManager({
        action: "transition_status",
        orderId: record.id,
        payload,
      });

      modal.success({
        title: translate("notifications.success"),
        content: translate("orders.saveSuccess"),
      });
      setManualWaybillMode(false);
      await refreshOrderState();
    } catch (err) {
      const msg = err instanceof Error ? err.message : translate("orders.saveError");
      modal.error({
        title: translate("notifications.error"),
        content: msg,
      });
    } finally {
      setSaving(false);
    }
  };

  const handleUpdate = (values: { status: string; waybill_number?: string; waybill_override_reason?: string }) => {
    if (values.status === "cancelled") {
      modal.confirm({
        title: translate("orders.cancelConfirm"),
        content: translate("orders.cancelContent"),
        okText: translate("orders.cancelOk"),
        cancelText: translate("orders.cancelButton"),
        okButtonProps: { danger: true },
        onOk: () => doMutate(values),
      });
      return;
    }
    doMutate(values);
  };

  const STATUS_OPTIONS = getStatusOptions(translate);
  const current = record?.status ?? "";
  const allowed = getAvailableOrderTransitions(current, {
    hasProviderManagedShipment,
    allowManualWaybillOverride: manualWaybillMode,
  });
  const baseOptions = isStatusDropdownLocked
    ? STATUS_OPTIONS.filter((opt) => opt.value === current)
    : STATUS_OPTIONS.filter((opt) => allowed.includes(String(opt.value)));
  const currentInOptions = baseOptions.some((opt) => opt.value === current);
  const availableStatusOptions = currentInOptions
    ? baseOptions
    : [...baseOptions, { value: current, label: translate(`orderStatus.${current}`, {}, formatDisplayLabel(current)) }];
  const hasRealNextStatusTransition = availableStatusOptions.some(
    (option) => option.value !== current,
  );
  const isSaveDisabled = isFormDisabled || !hasRealNextStatusTransition;

  useEffect(() => {
    if (record) {
      form.setFieldsValue({ status: record.status ?? "pending", waybill_number: record.waybill_number ?? "" });
    }
  }, [record, form]);

  const getActivityIcon = (action: string) => {
    switch (action) {
      case "payment_success": return <Tag color="green">$</Tag>;
      case "payment_updated": return <Tag color="orange">$</Tag>;
      case "status_update": return <Tag color="blue">↻</Tag>;
      case "sync_tracking": return <Tag color="cyan">⟳</Tag>;
      case "shipping_created": return <Tag color="purple">📦</Tag>;
      default: return <Tag>•</Tag>;
    }
  };

  const getActivityText = (activity: Activity) => {
    const statusFrom = activity.old_status
      ? translate(`orderStatus.${activity.old_status}`, {}, formatDisplayLabel(activity.old_status))
      : "-";
    const statusTo = activity.new_status
      ? translate(`orderStatus.${activity.new_status}`, {}, formatDisplayLabel(activity.new_status))
      : "-";
    const actor = translate(
      `orders.activity.actors.${activity.actor_type === "system" ? "system" : "admin"}`,
      {},
      activity.actor_type === "system" ? "System" : "Admin"
    );

    switch (activity.action) {
      case "payment_success":
        return translate("orders.activity.paymentSuccess", {}, "Payment verified successfully");
      case "payment_updated":
        return translate("orders.activity.paymentUpdated", {}, "Payment status updated");
      case "status_update":
        return translate(
          "orders.activity.statusUpdated",
          { actor, from: statusFrom, to: statusTo },
          `${actor} changed status: ${statusFrom} → ${statusTo}`
        );
      case "sync_tracking":
        return translate("orders.activity.trackingSynced", {}, "Tracking synced from Biteship");
      case "shipping_created":
        return translate("orders.activity.shippingCreated", {}, "Shipping order created in Biteship");
      default:
        return translate(
          "orders.activity.unknown",
          { action: activity.action, from: statusFrom, to: statusTo },
          `${activity.action}: ${statusFrom} → ${statusTo}`
        );
    }
  };

  const paymentTypeLabel = record?.payment_type
    ? translate(`orders.paymentTypes.${record.payment_type}`, {}, formatDisplayLabel(record.payment_type))
    : "-";
  const courierLabel = record?.courier_code ? getFallbackCourierOption(record.courier_code).label : "-";
  const courierServiceLabel = record?.courier_service ? formatDisplayLabel(record.courier_service) : null;
  const courierDescription = record?.courier_code
    ? `${courierLabel}${courierServiceLabel ? ` • ${courierServiceLabel}` : ""}${record.shipping_etd ? ` (${record.shipping_etd})` : ""}`
    : "-";
  const currentOrderStatusLabel = record?.status
    ? translate(`orderStatus.${record.status}`, {}, formatDisplayLabel(record.status))
    : "-";
  const currentPaymentStatusLabel = record?.payment_status
    ? translate(`paymentStatus.${record.payment_status}`, {}, formatDisplayLabel(record.payment_status))
    : "-";

  const getWaybillSourceBadge = () => {
    if (!record?.waybill_number) return null;
    const source = record.waybill_source;
    if (source === "manual") {
      return <Tag color="orange" style={{ marginLeft: 8 }}>{translate("orders.waybillSourceManual")}</Tag>;
    }
    if (hasBiteship) {
      return <Tag color="blue" style={{ marginLeft: 8 }}>{translate("orders.waybillSourceSystem")}</Tag>;
    }
    return null;
  };

  const columns = [
    { title: translate("orders.fields.product"), dataIndex: ["products", "name"], key: "product", render: (_: unknown, row: OrderItem) => row.products?.name ?? "-" },
    { title: translate("orders.fields.quantity"), dataIndex: "quantity", key: "quantity", width: 80 },
    { title: translate("orders.fields.unitPrice"), dataIndex: "price_at_purchase", key: "price", render: (v: string | number) => `Rp ${Number(v || 0).toLocaleString("id-ID")}` },
    { title: translate("orders.fields.subtotal"), key: "subtotal", render: (_: unknown, row: OrderItem) => `Rp ${(Number(row.price_at_purchase || 0) * (row.quantity || 0)).toLocaleString("id-ID")}` },
  ];

  return (
    <Show isLoading={isLoading}>
      <Title level={5}>{translate("orders.orderInfo")}</Title>
      <Descriptions bordered size="small" column={1}>
        <Descriptions.Item label={translate("orders.fields.id")}>{record?.id ?? "-"}</Descriptions.Item>
        <Descriptions.Item label={translate("orders.currentOrderStatus")}>
          <Tag color={STATUS_COLORS[record?.status ?? ""] ?? "default"}>
            {currentOrderStatusLabel}
          </Tag>
          {isStatusDropdownLocked && (
            <Tooltip title={translate("orders.tooltips.statusSystemControlled")}>
              <LockOutlined style={{ marginLeft: 8, color: "#999" }} />
            </Tooltip>
          )}
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.currentPaymentStatus")}>
          <Tag color={PAYMENT_COLORS[record?.payment_status ?? ""] ?? "default"}>
            {currentPaymentStatusLabel}
          </Tag>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.paymentType")}><Text>{paymentTypeLabel}</Text></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.midtransOrderId")}><Text copyable>{record?.midtrans_order_id ?? "-"}</Text></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.midtransTransactionId")}><Text copyable>{record?.midtrans_transaction_id ?? "-"}</Text></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.date")}><DateField value={record?.created_at} format="LLL" /></Descriptions.Item>
      </Descriptions>

      <Title level={5} style={{ marginTop: 24 }}>{translate("orders.totalAndShipping")}</Title>
      <Descriptions bordered size="small" column={1}>
        <Descriptions.Item label={translate("orders.fields.productSubtotal")}><NumberField value={record?.total_amount} options={{ style: "currency", currency: "IDR" }} /></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.shippingCost")}>{record?.shipping_cost != null ? `Rp ${Number(record.shipping_cost).toLocaleString("id-ID")}` : "-"}</Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.courier")}>{courierDescription}</Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.waybillNumber")}>
          <Space>
            <Text strong copyable={!!record?.waybill_number}>{record?.waybill_number ?? "-"}</Text>
            {getWaybillSourceBadge()}
          </Space>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.biteshipOrderId")}>
          <Text copyable>{record?.biteship_order_id ?? "-"}</Text>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.biteshipTrackingId")}>
          <Text copyable={!!record?.biteship_tracking_id}>{record?.biteship_tracking_id ?? "-"}</Text>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.updatedAt")}>{record?.updated_at ? <DateField value={record.updated_at} format="LLL" /> : "-"}</Descriptions.Item>
      </Descriptions>

      {biteshipExceptionInfo && (
        <Alert
          style={{ marginTop: 16 }}
          type={biteshipExceptionInfo.alertType}
          showIcon
          message={translate("orders.biteshipAlertTitle")}
          description={
            <Space direction="vertical" size={4}>
              <Text>
                {translate(
                  `orders.biteshipAlerts.${biteshipExceptionInfo.messageKey}`,
                  {},
                  translate("orders.biteshipAlertUnknown")
                )}
              </Text>
              <Text type="secondary">
                {translate("orders.biteshipAlertStatusLabel")}: {formatBiteshipStatusLabel(biteshipExceptionInfo.status)}
              </Text>
            </Space>
          }
        />
      )}

      <Card
        title={
          <span>
            {translate("orders.actionsTitle")}
            {isStatusDropdownLocked && (
              <Tooltip title={translate("orders.tooltips.webhookControlled")}>
                <InfoCircleOutlined style={{ marginLeft: 8, color: "#faad14" }} />
              </Tooltip>
            )}
          </span>
        }
        style={{ marginTop: 24 }}
      >
        <Text type="secondary">{translate("orders.actionsDescription")}</Text>
        <Descriptions bordered size="small" column={1} style={{ marginTop: 16, marginBottom: 16 }}>
        <Descriptions.Item label={translate("orders.currentOrderStatus")}>
            <Tag color={STATUS_COLORS[record?.status ?? ""] ?? "default"}>{currentOrderStatusLabel}</Tag>
          </Descriptions.Item>
          <Descriptions.Item label={translate("orders.currentPaymentStatus")}>
            <Tag color={PAYMENT_COLORS[record?.payment_status ?? ""] ?? "default"}>{currentPaymentStatusLabel}</Tag>
          </Descriptions.Item>
        </Descriptions>

        {canSyncTracking && (
          <Button type="default" icon={<SyncOutlined spin={syncing} />} onClick={handleSyncTracking} loading={syncing} style={{ marginBottom: 16 }}>
            {translate("orders.syncTracking")}
          </Button>
        )}

        {hasProviderManagedShipment && !manualWaybillMode && !isWaybillFullyLocked && (
          <Alert
            style={{ marginBottom: 16 }}
            type="info"
            showIcon
            message={translate("orders.providerManagedWaybillHelp")}
          />
        )}

        <Form form={form} layout="vertical" onFinish={handleUpdate} initialValues={{ status: record?.status ?? "pending", waybill_number: record?.waybill_number ?? "" }}>
          <Form.Item
            name="status"
            label={translate("orders.nextOrderStatus")}
            rules={[{ required: true }]}
            tooltip={isStatusDropdownLocked ? translate("orders.tooltips.statusSystemControlled") : undefined}
          >
            <Select options={availableStatusOptions} style={{ minWidth: 160 }} disabled={isStatusDropdownLocked || isSaveDisabled} />
          </Form.Item>

          {showManualWaybillToggle && (
            <Form.Item label={translate("orders.enableManualWaybill")}>
              <Switch
                size="small"
                checked={manualWaybillMode}
                onChange={setManualWaybillMode}
                checkedChildren={translate("orders.waybillModeManual")}
                unCheckedChildren={translate("orders.waybillModeAuto")}
              />
            </Form.Item>
          )}

          {showManualWaybillField && (
            <Form.Item
              name="waybill_number"
              label={translate("orders.fields.waybillNumber")}
              tooltip={isWaybillFullyLocked
                ? translate("orders.tooltips.waybillLocked")
                : isWaybillAutoGenerated
                  ? translate("orders.tooltips.waybillAuto")
                  : translate("orders.tooltips.waybillManual")}
              dependencies={["status"]}
              rules={[
                ({ getFieldValue }) => ({
                  validator(_, value) {
                    if (!requiresManualWaybillForSelectedStatus(String(getFieldValue("status") ?? ""))) {
                      return Promise.resolve();
                    }
                    if (String(value ?? "").trim()) return Promise.resolve();
                    const shippedStatusLabel = translate("orderStatus.shipped", {}, formatDisplayLabel("shipped"));
                    return Promise.reject(new Error(translate("orders.waybillRequired", { status: shippedStatusLabel })));
                  },
                }),
              ]}
            >
              <Input
                placeholder={translate("orders.waybillPlaceholder")}
                disabled={isWaybillInputDisabled || isSaveDisabled}
                suffix={isWaybillFullyLocked ? <LockOutlined style={{ color: "#999" }} /> : undefined}
              />
            </Form.Item>
          )}

          {showOverrideReason && (
            <>
              <Alert
                message={translate("orders.manualWaybillWarning")}
                type="warning"
                showIcon
                icon={<WarningOutlined />}
                style={{ marginBottom: 16 }}
              />
              <Form.Item
                name="waybill_override_reason"
                label={translate("orders.waybillOverrideReason")}
                rules={[{ required: true, message: translate("orders.waybillOverridePlaceholder") }]}
              >
                <Input.TextArea
                  placeholder={translate("orders.waybillOverridePlaceholder")}
                  rows={2}
                />
              </Form.Item>
            </>
          )}

          <Form.Item>
            <Button type="primary" htmlType="submit" loading={saving} disabled={isSaveDisabled}>
              {translate("buttons.save")}
            </Button>
          </Form.Item>
        </Form>
      </Card>

      <Title level={5} style={{ marginTop: 24 }}>{translate("orders.activityTitle")}</Title>
      <Card styles={{ body: { padding: "12px 24px" } }}>
        {loadingActivities ? <Spin /> : activities.length === 0 ? <Text type="secondary">{translate("orders.noActivities")}</Text> : (
          <Timeline items={activities.map((activity) => ({ dot: getActivityIcon(activity.action), children: <div><div>{getActivityText(activity)}</div><Text type="secondary" style={{ fontSize: 12 }}><DateField value={activity.created_at} format="DD/MM/YYYY HH:mm" /></Text></div> }))} />
        )}
      </Card>

      <Title level={5} style={{ marginTop: 24 }}>{translate("orders.productList")}</Title>
      <Table dataSource={items} columns={columns} rowKey="id" pagination={false} size="small" />
    </Show>
  );
};
