import { useCallback, useEffect, useState } from "react";
import { useShow, useTranslation } from "@refinedev/core";
import { Show, DateField, NumberField } from "@refinedev/antd";
import { Typography, Table, Tag, Descriptions, Form, Select, Input, Button, Card, App, Timeline, Spin, Tooltip, Switch, Alert, Space } from "antd";
import { SyncOutlined, InfoCircleOutlined, LockOutlined, WarningOutlined } from "@ant-design/icons";
import { STATUS_COLORS, PAYMENT_COLORS, getStatusOptions, TRANSITION_RULES } from "../../constants/orders";
import { supabaseClient } from "../../providers/supabase-client";
import { getFunctionsErrorMessage } from "../../utils/functions-error";

const { Title, Text } = Typography;

interface OrderItem {
  id: string;
  product_id: string;
  quantity: number;
  price_at_purchase: string | number;
  products?: { name: string } | null;
}

interface OrderRecord {
  id: string;
  user_id: string;
  total_amount: string | number;
  status: string;
  payment_status: string;
  shipping_cost?: string | number | null;
  courier_code?: string | null;
  courier_service?: string | null;
  shipping_etd?: string | null;
  waybill_number?: string | null;
  waybill_source?: string | null;
  payment_type?: string | null;
  midtrans_order_id?: string | null;
  midtrans_transaction_id?: string | null;
  biteship_order_id?: string | null;
  biteship_tracking_id?: string | null;
  created_at: string;
  updated_at?: string | null;
  order_items?: OrderItem[];
}

interface Activity {
  id: string;
  action: string;
  old_status: string | null;
  new_status: string | null;
  actor_type: string;
  metadata: Record<string, unknown>;
  created_at: string;
}

// Statuses where the status dropdown is locked (terminal states)
const TERMINAL_STATUSES = ["delivered", "cancelled"];
// Only lock for terminal statuses - shipped can still transition to delivered
const LOCKED_STATUSES = ["delivered", "cancelled"];

export const OrderShow: React.FC = () => {
  const { translate } = useTranslation();
  const {
    result: record,
    query: { isLoading },
  } = useShow<OrderRecord>({
    meta: { select: "*, order_items(*, products(name))" },
  });

  const { modal } = App.useApp();
  const [form] = Form.useForm<{ status: string; waybill_number?: string; waybill_override_reason?: string }>();
  const [activities, setActivities] = useState<Activity[]>([]);
  const [loadingActivities, setLoadingActivities] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [manualWaybillMode, setManualWaybillMode] = useState(false);

  const items = record?.order_items ?? [];
  const hasBiteship = !!record?.biteship_order_id;
  const currentStatus = record?.status ?? "";
  const canSyncTracking = hasBiteship && !TERMINAL_STATUSES.includes(currentStatus);

  // Status dropdown lock: only lock for terminal statuses (delivered, cancelled)
  // shipped CAN still transition to delivered, so don't lock it
  const isStatusDropdownLocked = LOCKED_STATUSES.includes(currentStatus);

  // Save button: disabled only for terminal statuses
  const isFormDisabled = TERMINAL_STATUSES.includes(currentStatus);

  // Waybill fully locked after shipped/delivered — no override possible
  const isWaybillFullyLocked = ["shipped", "delivered"].includes(currentStatus);

  // Waybill read-only by default when Biteship auto-generated it (unless manual mode toggled)
  const isWaybillAutoGenerated = hasBiteship && !!record?.waybill_number;
  const isWaybillInputDisabled = isWaybillFullyLocked || (isWaybillAutoGenerated && !manualWaybillMode);

  // Show override reason field when: manual mode is on AND Biteship order exists (i.e. overriding system waybill)
  const showOverrideReason = manualWaybillMode && hasBiteship && !isWaybillFullyLocked;

  const loadActivities = useCallback(async () => {
    if (!record?.id) return;
    setLoadingActivities(true);
    try {
      const { data, error } = await supabaseClient
        .from("order_activities")
        .select("*")
        .eq("order_id", record.id)
        .order("created_at", { ascending: false })
        .limit(20);

      if (!error && data) {
        setActivities(data as Activity[]);
      }
    } catch (err) {
      console.error("Failed to load activities:", err);
    } finally {
      setLoadingActivities(false);
    }
  }, [record?.id]);

  useEffect(() => {
    if (record?.id) {
      loadActivities();
    }
  }, [record?.id, loadActivities]);

  const invokeOrderManager = async (values: {
    action: "transition_status" | "sync_tracking";
    orderId: string;
    payload?: Record<string, unknown>;
  }) => {
    const { data, error } = await supabaseClient.functions.invoke("order-manager", {
      body: values,
    });
    if (error) {
      const msg = await getFunctionsErrorMessage(error, "Order manager request failed");
      throw new Error(msg);
    }
    return data;
  };

  const handleSyncTracking = async () => {
    if (!record?.biteship_order_id || !canSyncTracking) return;
    setSyncing(true);
    try {
      const result = await invokeOrderManager({
        action: "sync_tracking",
        orderId: record.id,
      });

      modal.success({
        title: translate("orders.trackingSynced"),
        content: `Status updated to ${result?.data?.status ?? "updated"}`,
      });
      loadActivities();
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      modal.error({ title: translate("orders.syncFailed"), content: msg });
    } finally {
      setSyncing(false);
    }
  };

  const doMutate = async (values: { status: string; waybill_number?: string; waybill_override_reason?: string }) => {
    if (!record?.id) return;

    setSaving(true);
    try {
      const payload: Record<string, unknown> = {
        to: values.status,
        waybill_number: values.waybill_number?.trim() || undefined,
      };

      // If manual waybill mode is on and there's a Biteship order, mark as manual override
      if (manualWaybillMode && hasBiteship && values.waybill_number?.trim()) {
        payload.waybill_source = "manual";
        payload.waybill_override_reason = values.waybill_override_reason?.trim() || undefined;
      } else if (values.waybill_number?.trim() && !hasBiteship) {
        payload.waybill_source = "manual";
      }

      await invokeOrderManager({
        action: "transition_status",
        orderId: record.id,
        payload,
      });

      modal.success({
        title: translate("notifications.success"),
        content: translate("orders.saveSuccess"),
      });
      setManualWaybillMode(false);
      loadActivities();
    } catch (err) {
      const msg = err instanceof Error ? err.message : translate("orders.saveError");
      modal.error({
        title: translate("notifications.error"),
        content: msg,
      });
    } finally {
      setSaving(false);
    }
  };

  const handleUpdate = (values: { status: string; waybill_number?: string; waybill_override_reason?: string }) => {
    if (values.status === "cancelled") {
      modal.confirm({
        title: translate("orders.cancelConfirm"),
        content: translate("orders.cancelContent"),
        okText: translate("orders.cancelOk"),
        cancelText: translate("orders.cancelButton"),
        okButtonProps: { danger: true },
        onOk: () => doMutate(values),
      });
      return;
    }
    doMutate(values);
  };

  const STATUS_OPTIONS = getStatusOptions(translate);
  const current = record?.status ?? "";
  const allowed = TRANSITION_RULES[current] ?? [];
  const baseOptions = isStatusDropdownLocked
    ? STATUS_OPTIONS.filter((opt) => opt.value === current)
    : STATUS_OPTIONS.filter((opt) => opt.value === current || allowed.includes(String(opt.value)));
  const currentInOptions = STATUS_OPTIONS.some((opt) => opt.value === current);
  const availableStatusOptions = currentInOptions
    ? baseOptions
    : [...baseOptions, { value: current, label: translate(`orderStatus.${current}`) }];

  useEffect(() => {
    if (record) {
      form.setFieldsValue({ status: record.status ?? "pending", waybill_number: record.waybill_number ?? "" });
    }
  }, [record, form]);

  const getActivityIcon = (action: string) => {
    switch (action) {
      case "payment_success": return <Tag color="green">$</Tag>;
      case "payment_updated": return <Tag color="orange">$</Tag>;
      case "status_update": return <Tag color="blue">↻</Tag>;
      case "sync_tracking": return <Tag color="cyan">⟳</Tag>;
      case "shipping_created": return <Tag color="purple">📦</Tag>;
      default: return <Tag>•</Tag>;
    }
  };

  const getActivityText = (activity: Activity) => {
    const statusFrom = activity.old_status ? translate(`orderStatus.${activity.old_status}`) : "-";
    const statusTo = activity.new_status ? translate(`orderStatus.${activity.new_status}`) : "-";
    const actor = activity.actor_type === "system" ? "Sistem" : "Admin";
    switch (activity.action) {
      case "payment_success": return "Pembayaran berhasil diverifikasi";
      case "payment_updated": return "Status pembayaran diperbarui";
      case "status_update": return `${actor} mengubah status: ${statusFrom} → ${statusTo}`;
      case "sync_tracking": return "Sync tracking dari Biteship";
      case "shipping_created": return "Order pengiriman dibuat di Biteship";
      default: return `${activity.action}: ${statusFrom} → ${statusTo}`;
    }
  };

  const getWaybillSourceBadge = () => {
    if (!record?.waybill_number) return null;
    const source = record.waybill_source;
    if (source === "manual") {
      return <Tag color="orange" style={{ marginLeft: 8 }}>{translate("orders.waybillSourceManual")}</Tag>;
    }
    if (hasBiteship) {
      return <Tag color="blue" style={{ marginLeft: 8 }}>{translate("orders.waybillSourceSystem")}</Tag>;
    }
    return null;
  };

  const columns = [
    { title: translate("orders.fields.product"), dataIndex: ["products", "name"], key: "product", render: (_: unknown, row: OrderItem) => row.products?.name ?? "-" },
    { title: translate("orders.fields.quantity"), dataIndex: "quantity", key: "quantity", width: 80 },
    { title: translate("orders.fields.unitPrice"), dataIndex: "price_at_purchase", key: "price", render: (v: string | number) => `Rp ${Number(v || 0).toLocaleString("id-ID")}` },
    { title: translate("orders.fields.subtotal"), key: "subtotal", render: (_: unknown, row: OrderItem) => `Rp ${(Number(row.price_at_purchase || 0) * (row.quantity || 0)).toLocaleString("id-ID")}` },
  ];

  return (
    <Show isLoading={isLoading}>
      <Title level={5}>{translate("orders.orderInfo")}</Title>
      <Descriptions bordered size="small" column={1}>
        <Descriptions.Item label={translate("orders.fields.id")}>{record?.id ?? "-"}</Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.status")}>
          <Tag color={STATUS_COLORS[record?.status ?? ""] ?? "default"}>
            {record?.status ? translate(`orderStatus.${record.status}`) : "-"}
          </Tag>
          {isStatusDropdownLocked && <Tooltip title="Status ini dikontrol oleh sistem (webhook)"><LockOutlined style={{ marginLeft: 8, color: "#999" }} /></Tooltip>}
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.paymentStatus")}>
          <Tag color={PAYMENT_COLORS[record?.payment_status ?? ""] ?? "default"}>{record?.payment_status ?? "-"}</Tag>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.paymentType")}><Text>{record?.payment_type ?? "-"}</Text></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.midtransOrderId")}><Text copyable>{record?.midtrans_order_id ?? "-"}</Text></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.midtransTransactionId")}><Text copyable>{record?.midtrans_transaction_id ?? "-"}</Text></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.date")}><DateField value={record?.created_at} format="LLL" /></Descriptions.Item>
      </Descriptions>

      <Title level={5} style={{ marginTop: 24 }}>{translate("orders.totalAndShipping")}</Title>
      <Descriptions bordered size="small" column={1}>
        <Descriptions.Item label={translate("orders.fields.productSubtotal")}><NumberField value={record?.total_amount} options={{ style: "currency", currency: "IDR" }} /></Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.shippingCost")}>{record?.shipping_cost != null ? `Rp ${Number(record.shipping_cost).toLocaleString("id-ID")}` : "-"}</Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.courier")}>{record?.courier_code ? `${record.courier_code} - ${record.courier_service ?? ""} (${record.shipping_etd ?? ""})` : "-"}</Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.waybillNumber")}>
          <Space>
            <Text strong copyable={!!record?.waybill_number}>{record?.waybill_number ?? "-"}</Text>
            {getWaybillSourceBadge()}
          </Space>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.biteshipOrderId")}>
          <Text copyable>{record?.biteship_order_id ?? "-"}</Text>
          {canSyncTracking && <Tooltip title={translate("orders.syncTracking")}><Button type="text" icon={<SyncOutlined spin={syncing} />} onClick={handleSyncTracking} loading={syncing} style={{ marginLeft: 8 }} size="small">Sync</Button></Tooltip>}
        </Descriptions.Item>
        <Descriptions.Item label="Biteship Tracking ID">
          <Text copyable={!!record?.biteship_tracking_id}>{record?.biteship_tracking_id ?? "-"}</Text>
        </Descriptions.Item>
        <Descriptions.Item label={translate("orders.fields.updatedAt")}>{record?.updated_at ? <DateField value={record.updated_at} format="LLL" /> : "-"}</Descriptions.Item>
      </Descriptions>

      <Card
        title={
          <span>
            {translate("orders.updateOrder")}
            {isStatusDropdownLocked && (
              <Tooltip title="Status tertentu dikontrol otomatis oleh webhook">
                <InfoCircleOutlined style={{ marginLeft: 8, color: "#faad14" }} />
              </Tooltip>
            )}
          </span>
        }
        style={{ marginTop: 24 }}
      >
        <Form form={form} layout="vertical" onFinish={handleUpdate} initialValues={{ status: record?.status ?? "pending", waybill_number: record?.waybill_number ?? "" }}>
          <Form.Item
            name="status"
            label={translate("orders.fields.status")}
            rules={[{ required: true }]}
            tooltip={isStatusDropdownLocked ? "Status ini dikontrol oleh sistem webhook" : undefined}
          >
            <Select options={availableStatusOptions} style={{ minWidth: 160 }} disabled={isStatusDropdownLocked || isFormDisabled} />
          </Form.Item>

          <Form.Item
            name="waybill_number"
            label={
              <Space>
                {translate("orders.fields.waybillNumber")}
                {isWaybillAutoGenerated && !isWaybillFullyLocked && (
                  <Tooltip title={translate("orders.enableManualWaybill")}>
                    <Switch
                      size="small"
                      checked={manualWaybillMode}
                      onChange={setManualWaybillMode}
                      checkedChildren="Manual"
                      unCheckedChildren="Auto"
                    />
                  </Tooltip>
                )}
              </Space>
            }
            tooltip={isWaybillFullyLocked ? "Resi terkunci setelah pengiriman" : isWaybillAutoGenerated ? "Nomor resi dari Biteship" : "Untuk kurir non-Biteship"}
            dependencies={["status"]}
            rules={[
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (getFieldValue("status") !== "shipped") return Promise.resolve();
                  if (String(value ?? "").trim()) return Promise.resolve();
                  return Promise.reject(new Error(translate("orders.waybillRequired", { status: "shipped" })));
                },
              }),
            ]}
          >
            <Input
              placeholder={translate("orders.waybillPlaceholder")}
              disabled={isWaybillInputDisabled || isFormDisabled}
              suffix={isWaybillFullyLocked ? <LockOutlined style={{ color: "#999" }} /> : undefined}
            />
          </Form.Item>

          {showOverrideReason && (
            <>
              <Alert
                message={translate("orders.manualWaybillWarning")}
                type="warning"
                showIcon
                icon={<WarningOutlined />}
                style={{ marginBottom: 16 }}
              />
              <Form.Item
                name="waybill_override_reason"
                label={translate("orders.waybillOverrideReason")}
                rules={[{ required: true, message: translate("orders.waybillOverridePlaceholder") }]}
              >
                <Input.TextArea
                  placeholder={translate("orders.waybillOverridePlaceholder")}
                  rows={2}
                />
              </Form.Item>
            </>
          )}

          <Form.Item>
            <Button type="primary" htmlType="submit" loading={saving} disabled={isFormDisabled}>
              {translate("buttons.save")}
            </Button>
          </Form.Item>
        </Form>
      </Card>

      <Title level={5} style={{ marginTop: 24 }}>{translate("orders.activityTitle")}</Title>
      <Card bodyStyle={{ padding: "12px 24px" }}>
        {loadingActivities ? <Spin /> : activities.length === 0 ? <Text type="secondary">{translate("orders.noActivities")}</Text> : (
          <Timeline items={activities.map((activity) => ({ dot: getActivityIcon(activity.action), children: <div><div>{getActivityText(activity)}</div><Text type="secondary" style={{ fontSize: 12 }}><DateField value={activity.created_at} format="DD/MM/YYYY HH:mm" /></Text></div> }))} />
        )}
      </Card>

      <Title level={5} style={{ marginTop: 24 }}>{translate("orders.productList")}</Title>
      <Table dataSource={items} columns={columns} rowKey="id" pagination={false} size="small" />
    </Show>
  );
};
